TITLES:
  NO-REGISTER:
    TITLE: '&aPlease Register'
    SUBTITLE: '&eUse /register password password'

  NO-LOGIN:
    TITLE: '&aPlease Login'
    SUBTITLE: '&eUse /login password'    

  ON-REGISTER:
    TITLE: '&aREGISTER COMPLETE'
    SUBTITLE: '&eRegister sucellyfull'
    TIME:
      FADEIN: 5
      STAY: 30
      FADEOUT: 5
      
  ON-LOGIN:
    TITLE: '&aLOGIN COMPLETE'
    SUBTITLE: '&eLogin sucellyfull'
    TIME:
      FADEIN: 5
      STAY: 30
      FADEOUT: 5
      
ACTIONBAR:
  NO_REGISTER:
    MESSAGE: '&7&CTimeleft: &e<time>'

  NO_LOGIN:
    MESSAGE: '&7&CTimeleft: &e<time>'
    
  ON_REGISTER:
    STAY: 30
    MESSAGE: '&eREGISTER COMPLETE! WELCOME %player_name%'

  ON_LOGIN:
    STAY: 30
    MESSAGE: '&aWELCOME BACK %player_name%'
